<?php

namespace AppBundle\Repository;

/**
 * aplicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aplicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
