<?php

namespace AppBundle\Repository;

/**
 * AplicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AplicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
