<?php

namespace AppBundle\Repository;

/**
 * empresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empresaRepository extends \Doctrine\ORM\EntityRepository
{
}
