<?php

namespace AppBundle\Repository;

/**
 * pasanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pasanteRepository extends \Doctrine\ORM\EntityRepository
{
}
