<?php

namespace AppBundle\Repository;

/**
 * PasanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasanteRepository extends \Doctrine\ORM\EntityRepository
{
}
