<?php

namespace AppBundle\Repository;

/**
 * VacanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacanteRepository extends \Doctrine\ORM\EntityRepository
{
}
